export const FETCH_PLACEHOLDERS_PENDING = 'FETCH_PLACEHOLDERS_PENDING';

export const FETCH_PLACEHOLDERS_FULFILLED = 'FETCH_PLACEHOLDERS_FULFILLED';

export const FETCH_PLACEHOLDERS_REJECTED = 'FETCH_PLACEHOLDERS_REJECTED';